#quarkus.http.host=0.0.0.0
#quarkus.http.port=8081

# H2 Database Console (for development)
#quarkus.datasource.db-kind=h2
#quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#quarkus.datasource.h2.console.enabled=true

# Hibernate settings
#quarkus.hibernate-orm.database.generation=drop-and-create
#quarkus.hibernate-orm.log.sql=true

# Load our sample data
#quarkus.hibernate-orm.sql-load-script=import.sql

# Alternative H2 console configuration (if above doesn't work)
# quarkus.h2.console.enabled=true
# MSSQL Settings
#quarkus.datasource.db-kind=mssql
#quarkus.datasource.username=SA
#quarkus.datasource.password=Guclutan54367671aA1!
#quarkus.datasource.jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=LibraryDB;encrypt=true;trustServerCertificate=true

#quarkus.hibernate-orm.database.generation=none

#quarkus.hibernate-orm.log.sql=true

quarkus.datasource.db-kind=mssql
quarkus.datasource.username=SA
quarkus.datasource.password=Guclutan54367671aA1!
quarkus.datasource.jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=LibraryDB;encrypt=true;trustServerCertificate=true

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.http.port=8081
quarkus.http.host=0.0.0.0